# Generated by Django 6.0.3 on 2026-03-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to='uploads/')),
                ('converted_file', models.FileField(blank=True, null=True, upload_to='conversions/')),
                ('conversion_type', models.CharField(choices=[('FORMAT', 'Format Conversion'), ('PDF', 'Convert to PDF'), ('WORD', 'Convert to Word')], max_length=10)),
                ('target_format', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
