# Generated by Django 6.0.3 on 2026-03-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageconversion',
            name='converted_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
